languageCode: en-us
title: Sacred Space in South Asia
baseURL: https://sacred-space-in-south-asia.netlify.app/
author:
  name: Nick Tackes
Params:
  background: ""
  surface: ""
  primary: ""
  secondary: ""
  accent: ""
  mapStyle: "https://tile.openstreetmap.org/{z}/{x}/{y}.png"
