languageCode: en-us
title: Sacred Space in South Asia
baseURL: https://cozy-meerkat-3a32bd.netlify.app/
author:
  name: Jameson Mannix
Params:
  background: "#ffffff"
  surface: "#960000"
  primary: ""
  secondary: ""
  accent: ""
  mapStyle: https://tile.openstreetmap.org/{z}/{x}/{y}.png
